# Generated by Django 2.2.2 on 2019-06-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch_offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('branch_office_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_offices.Branch_Offices')),
            ],
        ),
    ]
