#!/bin/bash

set -eu

command="$1"
case "${command}" in
  docker_build)
      rm -rf docker/ProjectLanguage
      cp -r src docker/
      cd docker
      docker build -t iap-hq-backend:0.1.0 .
      exit $?
      ;;
  up)
      docker-compose -f ./docker-compose.yml -p iap up
      exit $?
      ;;
  down)
      docker-compose -f ./docker-compose.yml -p iap down
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
