# Generated by Django 2.2.2 on 2019-06-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_Offices',
            fields=[
                ('branch_office_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_office_name', models.CharField(max_length=200)),
                ('branch_office_location', models.CharField(max_length=100)),
            ],
        ),
    ]
